### ISSUE TITLE
Does not work with Unity Universal Render Pipeline (URP)

### ISSUE THREAD

**Issue by matt-d-rat** [Ending2015a/kage#1]
I came across this example project for casting shadows to an invisible plane and it is exactly what I needed as a reference point for my own project! However, my project relies on the universal render pipeline in Unity (2020.3.6f1), and thus the `TransparentShadow` shader is not compatible with how lighting works in URP.

I am not that familiar with shader code myself, so it is difficult for me to say exactly what the problem is, so I was wondering whether you would consider updating the project, to show how to get this approach to work with a unity project that uses the universal render pipeline?

I look forward to hearing from you.

**Comment by Ending2015a** [comment]
Hello, @matt-d-rat 
The shader in this repo only works for build-in render pipeline. But someone has already figured out the solution for URP here:
https://forum.unity.com/threads/water-shader-graph-transparency-and-shadows-universal-render-pipeline-order.748142/#post-5518747
